version: "2"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.9
    expose:
      - "9200"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - xpack.security.enabled=0

  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.9
    expose:
      - "5601"
    ports:
      - 5601:5601
    links:
      - elasticsearch
    environment:
      - xpack.security.enabled=0
