version: '2'
services:
  elasticsearch:
    image: elasticsearch:5.2.0-alpine
    expose:
      - "9200"
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: kibana
    ports:
      - 5601:5601
    links:
      - elasticsearch

